name: Release
on:  
  push:
    tags:
      - '*'
      
jobs:
  build_for_release:
    uses: ./.github/workflows/build.yml
  
  release:
    runs-on: ubuntu-latest
    needs: build_for_release
    permissions:
      contents: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          files: "*/*Release*.img"
          fail_on_unmatched_files: true
          generate_release_notes: true
          append_body: true
          body: |
            ## Usage
            Flash the board-specific image to SPINOR with rkdevtool / rkdeveloptool or to an EMMC / SD card.
            If your board is not yet supported, using a similar image may work but beware of potential issues.

            Debug builds can be found in the artifacts of the workflow run for this release.
